### ISSUE TITLE
Unable to get demo working

### ISSUE THREAD

**Issue by wiserweb** [PhilippSpo/meteor-encryption-demo#2]
Any guidance on how  to get this demo working?

Here's are the steps I tried:

$ git clone https://github.com/PhilippSpo/meteor-encryption-demo
$ meteor
aldeed:collection2  upgraded from 2.3.3 to 2.5.0
ReferenceError: SimpleSchema is not defined
$ meteor add aldeed:simple-schema
$ meteor 
ReferenceError: SimpleSchema is not defined
$ meteor update
Changes to your project's package version selections from updating the release:

accounts-base           upgraded from 1.2.0 to 1.2.1
accounts-password       upgraded from 1.1.1 to 1.1.3
autoupdate              upgraded from 1.2.1 to 1.2.3
babel-compiler          added, version 5.8.24_1
babel-runtime           added, version 0.1.4
base64                  upgraded from 1.0.3 to 1.0.4
binary-heap             upgraded from 1.0.3 to 1.0.4
blaze                   upgraded from 2.1.2 to 2.1.3
blaze-tools             upgraded from 1.0.3 to 1.0.4
boilerplate-generator   upgraded from 1.0.3 to 1.0.4
caching-compiler        added, version 1.0.0
caching-html-compiler   added, version 1.0.1
callback-hook           upgraded from 1.0.3 to 1.0.4
check                   upgraded from 1.0.5 to 1.0.6
coffeescript            upgraded from 1.0.6 to 1.0.9
ddp                     upgraded from 1.1.0 to 1.2.2
ddp-client              added, version 1.2.1
ddp-common              added, version 1.2.1
ddp-rate-limiter        added, version 1.0.0
ddp-server              added, version 1.2.1
deps                    upgraded from 1.0.7 to 1.0.9
diff-sequence           added, version 1.0.1
ecmascript              added, version 0.1.4
ecmascript-collections  added, version 0.1.6
ejson                   upgraded from 1.0.6 to 1.0.7
email                   upgraded from 1.0.6 to 1.0.7
fastclick               upgraded from 1.0.3 to 1.0.7
geojson-utils           upgraded from 1.0.3 to 1.0.4
html-tools              upgraded from 1.0.4 to 1.0.5
htmljs                  upgraded from 1.0.4 to 1.0.5
http                    upgraded from 1.1.0 to 1.1.1
id-map                  upgraded from 1.0.3 to 1.0.4
jquery                  upgraded from 1.11.3_2 to 1.11.4
json                    removed from your project
launch-screen           upgraded from 1.0.2 to 1.0.4
livedata                upgraded from 1.0.13 to 1.0.15
localstorage            upgraded from 1.0.3 to 1.0.5
logging                 upgraded from 1.0.7 to 1.0.8
meteor                  upgraded from 1.1.6 to 1.1.7
meteor-platform         upgraded from 1.2.2 to 1.2.3
minifiers               upgraded from 1.1.5 to 1.1.7
minimongo               upgraded from 1.0.8 to 1.0.9
mobile-status-bar       upgraded from 1.0.3 to 1.0.6
mongo                   upgraded from 1.1.0 to 1.1.1
mongo-id                added, version 1.0.1
npm-mongo               added, version 1.4.39_1
observe-sequence        upgraded from 1.0.6 to 1.0.7
ordered-dict            upgraded from 1.0.3 to 1.0.4
promise                 added, version 0.4.8
random                  upgraded from 1.0.3 to 1.0.4
rate-limit              added, version 1.0.0
reactive-dict           upgraded from 1.1.0 to 1.1.1
reactive-var            upgraded from 1.0.5 to 1.0.6
reload                  upgraded from 1.1.3 to 1.1.4
retry                   upgraded from 1.0.3 to 1.0.4
routepolicy             upgraded from 1.0.5 to 1.0.6
service-configuration   upgraded from 1.0.4 to 1.0.5
session                 upgraded from 1.1.0 to 1.1.1
sha                     upgraded from 1.0.3 to 1.0.4
spacebars               upgraded from 1.0.6 to 1.0.7
spacebars-compiler      upgraded from 1.0.6 to 1.0.7
srp                     upgraded from 1.0.3 to 1.0.4
templating              upgraded from 1.1.1 to 1.1.3
templating-tools        added, version 1.0.0
tracker                 upgraded from 1.0.7 to 1.0.8
ui                      upgraded from 1.0.6 to 1.0.8
underscore              upgraded from 1.0.3 to 1.0.4
url                     upgraded from 1.0.4 to 1.0.5
webapp                  upgraded from 1.2.0 to 1.2.2
webapp-hashing          upgraded from 1.0.3 to 1.0.5

meteor-encryption-demo: updated to Meteor 1.2.0.1.

-- Notice --                                  

1.2: Meteor 1.2 includes many changes and improvements to the build system, some of which might require small changes to apps
     and packages. Please read the guide about breaking changes here:
     https://github.com/meteor/meteor/wiki/Breaking-changes-in-Meteor-1.2

Changes to your project's package version selections from updating package versions:

aldeed:autoform                upgraded from 5.4.0 to 5.5.1
arillo:flow-router-helpers     upgraded from 0.4.1 to 0.4.5
blaze-html-templates           added, version 1.0.1
cosmos:browserify              upgraded from 0.5.0 to 0.5.1
gildaspk:autoform-materialize  upgraded from 0.0.21 to 0.0.25
hot-code-push                  added, version 1.0.0
idorecall:email-normalize      added, version 1.0.0
jparker:gravatar               upgraded from 0.3.1 to 0.4.1
kadira:blaze-layout            upgraded from 2.0.0 to 2.1.0
kadira:flow-router             upgraded from 2.1.1 to 2.6.2
lbee:moment-helpers            upgraded from 1.1.0 to 1.2.0
matb33:collection-hooks        upgraded from 0.7.13 to 0.7.15
materialize:materialize        upgraded from 0.97.0 to 0.97.1
meteor-base                    added, version 1.0.1
meteor-platform                removed from your project
meteorhacks:subs-manager       upgraded from 1.5.2 to 1.6.2
mobile-experience              added, version 1.0.1
planifica:encryption           upgraded from 0.0.1 to 0.0.5
standard-minifiers             added, version 1.0.0
stolinski:stylus-multi         upgraded from 1.3.4 to 1.4.3
useraccounts:core              upgraded from 1.12.0 to 1.12.3
useraccounts:flow-routing      upgraded from 1.12.0 to 1.12.3
useraccounts:materialize       upgraded from 1.12.0 to 1.12.3
zimme:active-route             upgraded from 2.3.0 to 2.3.2

Newer versions of the following indirect dependencies are available:
- babrahams:editable-json 0.4.3 (0.6.0 is available)
- cosmos:browserify 0.5.1 (0.7.0 is available)
- matb33:collection-hooks 0.7.15 (0.8.0 is available)
- softwarerero:accounts-t9n 1.0.9 (1.1.4 is available)
  To update one or more of these packages, pass their names to `meteor update`.

$ meteor reset
$ meteor
=> Started proxy.  
=> Started MongoDB.  
=> Started your app.                          

=> App running at: http://localhost:3000/

Blank page loads in browser.
Javascript console displays many errors:

TypeError: Package['materialize:materialize'] is undefined  
Materialize = Package['materialize:materialize'].Materialize;

global-...fc34038 (line 8, col 1)
ReferenceError: Template is not defined

keyGenL...1c53f20 (line 2, col 1)
ReferenceError: Template is not defined

menu.co...7719a87 (line 2, col 1)
ReferenceError: Template is not defined

menuIte...ed8f85c (line 2, col 1)
ReferenceError: Template is not defined

userAre...0444f73 (line 2, col 1)
ReferenceError: Template is not defined

dialogA...2096e36 (line 2, col 1)
ReferenceError: Template is not defined

globalL...1dfdd03 (line 2, col 1)
ReferenceError: Template is not defined

hamburg...c65f023 (line 2, col 1)
ReferenceError: Template is not defined

TypeError: Materialize is undefined

**Comment by PhilippSpo** [comment]
Sorry the encryption package was still on version 0.0.1 which was missing some dependencies. Should be fixed now.

**Comment by wiserweb** [comment]
Tested and confirmed working.

Thanks!
